#!/usr/bin/python3
import sqlite3,sys

if len(sys.argv) != 2 :
	print("Usage:",sys.argv[0],"\"actor's name\"")
	sys.exit(1)

actor = sys.argv[1]

con = sqlite3.connect('a2.db')

cur = con.cursor()

cur.execute('SELECT m.title, d.name, m.year, m.content_rating, r.imdb_score '
			'FROM movie m '
			'JOIN acting ac ON (m.id = ac.movie_id) '
			'JOIN actor a ON (a.id = ac.actor_id) '
			'LEFT JOIN director d ON (d.id = m.director_id) '
			'JOIN rating r ON (r.movie_id = m.id) '
			"WHERE a.name = '%s' COLLATE NOCASE "
			'ORDER BY m.year, m.title ASC'%actor)

i = 1
while True:
	t = cur.fetchone()
	if t == None:
		break
	a,b,c,d,e = t
	if b == None: #no director
		a = a.strip()
		print('{}. {} -- ({}, {}, {})'.format(i,a,c,d,e))
	else:
		print('{}. {} -- {} ({}, {}, {})'.format(i,a,b,c,d,e))
	i+=1

con.close()