#!/usr/bin/python3
import sqlite3,sys

if len(sys.argv) != 2 :
	print("Usage:",sys.argv[0],"\"movie title\"")
	sys.exit(1)

title = sys.argv[1]

title = '%' + title
title = title + '%'

con = sqlite3.connect('a2.db')

cur = con.cursor()

cur.execute('SELECT m.title, m.year, m.content_rating, r.imdb_score, '
			'GROUP_CONCAT (g.genre) '
			'FROM movie m '
			'JOIN rating r ON (m.id = r.movie_id) '
			'JOIN genre g ON (g.movie_id = m.id) ' 
			"WHERE m.title LIKE '%s'"
			'GROUP BY m.title '
			'ORDER BY m.year, m.content_rating, m.title ASC'%title)

i = 1
end = []
while True:
	t = cur.fetchone()
	if t == None:
    	break
	
	a,b,c,d,e = t
	
	if b == None:
  		end.append(t)
  		continue
	
	print('{}. {} ({} {}, {}) [{}]'.format(i,a,b,c,d,e))
	i+=1

for j in range(0, len(end)):
	t = end[j]
	
	if t == None:
		break
	
	a,b,c,d,e = t
	print('{}. {} ({}, {}) [{}]'.format(i,a,c,d,e))
	i += 1

con.close()
#'GROUP BY m.title '